命令稿啟動於 2016年03月08日 (週二) 20時52分33秒
[01;32mkai@kai-VirtualBox[01;34m ~/lab1 $[00m whoamil[K;pwd
kai
/home/kai/lab1
[01;32mkai@kai-VirtualBox[01;34m ~/lab1 $[00m git config -;[Kl
user.name=F74046268
user.email=kai81275@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
[01;32mkai@kai-VirtualBox[01;34m ~/lab1 $[00m git clone https://github.com/F74046268/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[01;32mkai@kai-VirtualBox[01;34m ~/lab1 $[00m 
命令稿已於 2016年03月08日 (週二) 20時53分15秒
 完成